### PR TITLE
simulateBuy performance issue fix

### PR DESCRIPTION
**Pull request by SyDr**
Should be fast enough now (Issue: #25)

### CODE REVIEW

**Comment by Anahkiasen** [comment]
Thanks!

**Comment by Dasonk** [comment]
When will these changes get merged into master?  Alternatively when will the instructions for how to use the development build get updated?

**Comment by Anahkiasen** [comment]
Let me update the docs and do a release right now

**Comment by Anahkiasen** [comment]
Wait actually the contributing docs should be up to date, what did you find was missing ?

**Comment by Dasonk** [comment]
https://github.com/Anahkiasen/cookie-monster/issues/15 <- This.  I still don't see any directions on how to actually use the development build via bookmarklet or another method.  Unless it's already grabbing from the development build?  Either way the README isn't up to date.

**Comment by Anahkiasen** [comment]
Oh ok no I thought you meant contributing like working on the code. Yeah I still need to create a separate branch on the server.

**Comment by Dasonk** [comment]
That would be highly appreciated.  It would be especially useful during these times where Cookie Clicker itself goes through some changes.  At the moment there are some bugs in CM that I'm not sure have been addressed in the development build yet and I have no way of checking.  Also with the bug fixes coming quickly it would be nice to use the bleeding edge version...

**Comment by davidgro** [comment]
Any word on this? And by 'this' I mean either or both of releasing the fix to Master, or making Develop directly loadable (or at least providing directions on how to load it)

**Comment by Anahkiasen** [comment]
Yup! Sorry, was waiting for the domain's DNS to propagate : http://dev.cookie-monster.autopergamene.eu/

Will release a new version now

**Comment by davidgro** [comment]
Hmm. I copied my bookmarklet and added a "dev." to the url, but the fix for #25 either isn't there or doesn't work.  Is there any way I can confirm that it actually loaded the develop branch?

EDIT: Oh, of course - The Wrinkler stats. I am Not seeing the develop branch at http://dev.cookie-monster.autopergamene.eu/cookie-monster.min.js

**Comment by davidgro** [comment]
Ping.
#25 really is serious, I would very much like to be able to test the fix, and if it's good, have a version of CM that is usable when I reset!

**Comment by Anahkiasen** [comment]
Released a new version on master, can you check if it's better ?

**Comment by davidgro** [comment]
Yes, much! Thank you!

**Pull request merged**
