### PR TITLE
Reindeer notification

### PR DESCRIPTION
**Pull request by Jaytn**
Added sound when a reindeer pops up.
Hope doesn't break anything.

### CODE REVIEW

**Comment by Anahkiasen** [comment]
Argh, I just completed that on the develop branch, with the Reindeer timer bar and all. But you got me by this close :D You can take a look on develop/ see if you see anything in the current implementation that's missing from yours.

**Comment by Jaytn** [comment]
I just made this for fun (in the late hours) to see if I can get something together that works^^
I had no time to check yet but I am sure yours is better so take that ;)

**Comment by Anahkiasen** [comment]
Thanks a lot nonetheless, you are officially the first contributor so, thanks :+1:

**Comment by Andreasvb** [comment]
Not sure if it's live yet, it still says 1.040.01 when running.
Also, the bottom bar is enabled on load, even if it's Off in Settings.

Forgot to mention that all timers except Next Cookie are empty.

**Comment by Anahkiasen** [comment]
Ah yeah, should be fixed now. thanks.

**Comment by Andreasvb** [comment]
Thanks.

Not sure if the mini version is linked to the regular.
Code contains: CookieMonster={version:"v.1.040.01"

The instructions point to /master/dist/cookie-monster.min.js
Should I replace that with the correct /js/ path instead?

**Comment by Anahkiasen** [comment]
Hm no, it seems the minification didn't happen properly. I rebuilt the files, you should have the latest version now.

**Comment by Andreasvb** [comment]
It works now, but it skips like crazy. :P
Try with e.g. 4 fps, same in IE, Maxthon, Chrome.
Have you tried it, same for you?

**Comment by Anahkiasen** [comment]
Yeah I'm working on a huge refactor of the tooltips so it might be a little unstable right in the middle of it but I had to release some bugfixes that were done in the meantime.

**Comment by Andreasvb** [comment]
Oh, ok, will use Cookie Master in the meantime. :D
Thanks a lot, though!

**Comment by Jaytn** [comment]
And I thought I broke something with my reindeer sound :D

**Comment by Anahkiasen** [comment]
Ok I just spent a lot of time doing performance work : introduced a cache system, reducing the number of repaints and calls to `.html()`, tooltips that were computed for nothing. @Andreasvb can you tell me if it's better for you, with the code on the `develop` branch ?

At least I have better performances in the Chrome profiler.
For a 10s profile, measuring the active time (ie. the time CM passes doing stuff all around the place) at **30fps** :

| Original script | New refactor |
| --- | --- |
| 64% | 15% |

Less is better here, that means during 10s, to keep a steady flow of informations, the new version will work for 2s and not compute anything for the remaining 8, having a much smaller impact on the performances.

**Comment by Andreasvb** [comment]
Seems to work really well now!

**Pull request closed without merging**
